CREATE TABLE patients (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_ref     TEXT NOT NULL,
  age             INT CHECK (age BETWEEN 0 AND 120),
  chief_complaint TEXT NOT NULL,
  pain_scale      INT CHECK (pain_scale BETWEEN 1 AND 10),
  duration        TEXT,
  conditions      TEXT[],
  submitted_at    TIMESTAMPTZ DEFAULT now(),
  ai_level        TEXT CHECK (ai_level IN ('CRITICAL','HIGH','MEDIUM','LOW','UNCLASSIFIED')),
  ai_confidence   INT CHECK (ai_confidence BETWEEN 0 AND 100),
  ai_reasoning    TEXT,
  ai_actions      TEXT[],
  ai_source       TEXT CHECK (ai_source IN ('openai','rule-based','unclassified')),
  final_level     TEXT CHECK (final_level IN ('CRITICAL','HIGH','MEDIUM','LOW','UNCLASSIFIED')),
  confirmed_by    UUID REFERENCES staff(id),
  confirmed_at    TIMESTAMPTZ,
  seen_at         TIMESTAMPTZ,
  status          TEXT DEFAULT 'waiting' CHECK (status IN ('waiting','confirmed','seen'))
);
